language: objective-c
osx_image: xcode13.1

xcode_workspace: Rondo-iOS.xcworkspace
xcode_scheme: Rondo-iOS
xcode_destination: platform=iOS Simulator,OS=15.0,name=iPhone 12

cache: cocoapods
podfile: Podfile
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - gem install bundler

install:
  - bundle install
  - bundle update fastlane
  - pod install --repo-update
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  - bundle exec fastlane install_certificates
  - bundle exec fastlane match appstore

script:
  - bundle exec fastlane release

deploy:
  - provider: script
    skip_cleanup: true
    script: bundle exec fastlane testflight
    on:
      condition: '-n "$LEANPLUM_SDK_VERSION"'
      all_branches: true
  - provider: releases
    name: "Rondo iOS SDK $LEANPLUM_SDK_VERSION"
    tag: "$LEANPLUM_SDK_VERSION"
    api_key: "$GITHUB_TOKEN"
    file: "/Users/travis/build/Leanplum/Rondo-iOS/Rondo-iOS.ipa"
    skip_cleanup: true
    on:
      branch: master
      condition: '-n "$LEANPLUM_SDK_VERSION"'
