language: objective-c
osx_image: xcode10

xcode_workspace: Rondo-iOS.xcworkspace
xcode_scheme: Rondo-iOS
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X

cache: cocoapods
podfile: Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install
