language: objective-c
osx_image: xcode11.3

xcode_workspace: Rondo-iOS.xcworkspace
xcode_scheme: Rondo-iOS
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X

cache: cocoapods
podfile: Podfile
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - gem install bundler

install:
  - bundle install
  - pod install --repo-update

script:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  - bundle exec fastlane beta

after_success:
  - ./Tools/package.sh